name: Auto Format Go Code

on:
  push:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'


      - name: Format Go code
        run: gofmt -w -s .


      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: auto format go code"
          committer_name: github-actions[bot]
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com